### ISSUE TITLE
As SO, I want links to Localist to open in a new window when using the list style display without thubmails

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express_localist_bundle#14]
BSI pointed out that there wasn't a link in that display without the thumbnails.  @kevincrafts did a quick fix, but the "View Details" link doesn't open in a new window even when that option is checked in the block configuration.

![biological_sciences_initiative___university_of_colorado_boulder___university_of_colorado_boulder](https://user-images.githubusercontent.com/385234/33455555-ae233646-d5d9-11e7-8e33-9a6e990628b2.png)

**Comment by kevincrafts** [comment]
fixed this in https://github.com/CuBoulder/localist_widget_templates
